import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { authService } from '../services/auth';
import { useAuth } from './AuthContext';

export type AppLanguage = 'en' | 'fr';

type Dictionary = Record<string, string>;

const dictionaries: Record<AppLanguage, Dictionary> = {
  en: {
    settings: 'Settings',
    home: 'Home',
    messaging: 'Messaging',
    store: 'Store',
    dashboard: 'Dashboard',
    menu: 'Menu',
    account: 'Account',
    preferences: 'Preferences',
    support_legal: 'Support & Legal',
    language: 'Language',
    theme: 'Theme',
    help_center: 'Help Center',
    choose_language: 'Choose your preferred language',
    english: 'English',
    french: 'Français',
    save_changes: 'Save Changes',
    confirm_booking: 'Confirm Booking',
    update_personal_info: 'Update your personal information',
    manage_addresses: 'Manage Addresses',
    add_edit_locations: 'Add or edit your saved locations',
    payment_methods: 'Payment Methods',
    manage_payment_options: 'Manage your payment options',
    choose_app_appearance: 'Choose your app appearance',
    help_privacy_terms_about: 'Help, Privacy, Terms, About',
    select_date: 'Select a date',
    back: 'Back',
    is_coming_soon: 'is coming soon',
    we_are_working_to_bring: 'We are working hard to bring',
    to_you_stay_tuned: 'to you. Stay tuned!',
    close: 'Close',
    search_placeholder: 'Search for car wash services…',
    book_now: 'Book Now',
    book: 'Book',
    km_away: 'km away',
    location_permission: 'Location Permission',
    permission_denied_msg: 'Permission denied. Using default city center.',
    profile: 'Profile',
    welcome_guest: 'Welcome, Guest!\n',
    guest_prompt: 'Sign in or create an account to access your profile and booking history',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    continue_as_guest: 'Continue as Guest',
    service_provider: 'Service Provider',
    customer: 'Customer',
    member_since: 'Member since',
    your_stats: 'Your Stats',
    rating_label: 'Rating',
    jobs_done: 'Jobs Done',
    contact_information: 'Contact Information',
    email: 'Email',
    phone: 'Phone',
    location: 'Location',
    account_label: 'Account',
    change_password: 'Change Password',
    worker_dashboard: 'Worker Dashboard',
    sign_out: 'Sign Out',
    sign_out_confirm_title: 'Sign Out',
    sign_out_confirm_message: 'Are you sure you want to sign out?',
    error: 'Error',
    failed_sign_out: 'Failed to sign out. Please try again.',
    recently: 'Recently',
    date: 'Date',
    time: 'Time',
    enter_your_address: 'Enter your address',
    the_worker_will_come_to_this_location_to_wash_your_car: 'The worker will come to this location to wash your car',
    select_time: 'Select time',
    select_vehicle_type: 'Select vehicle type',
    any_special_instructions_or_requests: 'Any special instructions or requests?',
    missing_fields: 'Missing fields',
    please_complete: 'Please complete',
    worker_not_found: 'Worker not found',
    please_select_worker_again: 'Please go back and select a worker again.',
    // Booking Confirmation
    booking_confirmed: 'Booking Confirmed!',
    scheduled_message: 'Your car wash service has been scheduled',
    booking_id: 'Booking ID',
    your_car_washer: 'Your Car Washer',
    professional_car_washer: 'Professional Car Washer',
    confirmed: 'Confirmed',
    booking_details: 'Booking Details',
    service_location: 'Service Location',
    date_time: 'Date & Time',
    at: 'at',
    vehicle_type: 'Vehicle Type',
    payment_method: 'Payment Method',
    cash_on_delivery: 'Cash on Delivery',
    additional_notes: 'Additional Notes',
    total_amount: 'Total Amount',
    to_be_paid_upon_completion: 'To be paid upon service completion',
    important_information: 'Important Information',
    info_line_1: '• The worker will arrive at your location 5-10 minutes before the scheduled time',
    info_line_2: '• Please ensure water access is available at the service location',
    info_line_3: '• Payment is due upon completion of the service',
    info_line_4: '• You can contact the worker directly if needed',
    view_my_bookings: 'View My Bookings',
    back_to_home: 'Back to Home',
    // Bookings screen
    my_bookings: 'My Bookings',
    tab_all: 'All',
    tab_upcoming: 'Upcoming',
    tab_active: 'Active',
    tab_completed: 'Completed',
    no_bookings_found: 'No bookings found',
    no_bookings_yet: "You haven't made any bookings yet",
    no_status_bookings: 'No {status} bookings at the moment',
    book_a_service: 'Book a Service',
    booked_on: 'Booked on',
    call: 'Call',
    chat: 'Chat',
    rate_service: 'Rate Service',
    status_pending: 'Pending',
    status_confirmed: 'Confirmed',
    status_in_progress: 'In Progress',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    // Review Screen
    how_was_service: 'How was your service?',
    tap_stars_to_rate: 'Tap the stars to rate your experience',
    excellent: 'Excellent!',
    very_good: 'Very Good!',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    what_went_well: 'What went well?',
    what_went_wrong: 'What went wrong?',
    select_all_apply: 'Select all that apply (optional)',
    write_review: 'Write a Review',
    share_experience: 'Share more about your experience (optional)',
    review_placeholder: 'Tell us about your experience...',
    characters: 'characters',
    review_tips: 'Review Tips',
    tip_specific: 'Be specific about what you liked or disliked',
    tip_constructive: 'Keep feedback constructive and respectful',
    tip_helpful: 'Your review helps others make informed decisions',
    submitting: 'Submitting...',
    submit_review: 'Submit Review',
    review_submitted: 'Review Submitted',
    thank_you_feedback: 'Thank you for your feedback!',
    booking: 'Booking',
    // Review Tags - Positive
    tag_professional: 'Professional',
    tag_on_time: 'On Time',
    tag_thorough: 'Thorough',
    tag_friendly: 'Friendly',
    tag_quality: 'Great Quality',
    tag_value: 'Good Value',
    // Review Tags - Negative
    tag_late: 'Late Arrival',
    tag_rushed: 'Rushed Job',
    tag_incomplete: 'Incomplete',
    tag_unprofessional: 'Unprofessional',
    tag_expensive: 'Overpriced',
    tag_damage: 'Caused Damage',
    // Login Screen
    welcome_back: 'Welcome Back',
    sign_in_to_book: 'Sign in to book your car wash service',
    enter_your_email: 'Enter your email',
    enter_your_password: 'Enter your password',
    password: 'Password',
    confirm_password: 'Confirm Password',
    forgot_password: 'Forgot Password?',
    signing_in: 'Signing in...',
    dont_have_account: "Don't have an account?",
    sign_up: 'Sign Up',
    login_failed: 'Login failed',
    check_credentials: 'Please check your credentials and try again.',
    // Signup Screen
    join_us_to_book: 'Join us to book professional car wash services',
    enter_full_name: 'Enter your full name',
    enter_email: 'Enter your email',
    phone_number: 'Phone Number',
    enter_phone_number: 'Enter your phone number',
    create_password: 'Create a password',
    confirm_your_password: 'Confirm your password',
    please_confirm_password: 'Please confirm your password',
    i_agree_to: 'I agree to the',
    creating_account: 'Creating account...',
    already_have_account: 'Already have an account?',
    passwords_dont_match: "Passwords don't match",
    passwords_must_match: 'Please make sure both passwords are identical.',
    terms_not_accepted: 'Terms not accepted',
    agree_to_terms: 'Please agree to the terms and conditions to continue.',
    signup_failed: 'Signup failed',
    verify_your_email: 'Verify your email',
    verification_email_sent: 'We sent a verification link to {email}.\nOpen your email, confirm your account, then log in.',
    email_already_registered: 'This email is already registered. Please sign in or use a different email.',
    invalid_email: 'Please enter a valid email address.',
    weak_password: 'Your password does not meet the requirements.',
    // Services
    services_title: 'Services',
    services_subtitle: 'Choose a service that fits your car',
    view_details: 'View details',
    service_basic_title: 'Basic Wash',
    service_basic_desc: 'Exterior wash and dry',
    service_deluxe_title: 'Deluxe Wash',
    service_deluxe_desc: 'Exterior + interior clean',
    service_deep_title: 'Deep Clean',
    service_deep_desc: 'Full detailing in/out',
    service_interior_title: 'Interior Detail',
    service_interior_desc: 'Vacuum and interior detail',
    service_pro_title: 'Pro Package',
    service_pro_desc: 'Rinse, wax, and shine',
    // Service Detail
    service_not_found: 'Service not found.',
    go_back: 'Go back',
    whats_included: 'What’s included',
    include_line_1: '• High-pressure rinse',
    include_line_2: '• pH-neutral shampoo',
    include_line_3: '• Soft microfiber hand wash and dry',
    include_line_4: '• Windows and mirrors cleaning',
    include_line_5: '• Tyre shine and exterior finishing',
    notes: 'Notes',
    notes_body: 'Duration depends on vehicle size and condition. Prices may vary by provider. You can select a worker from the Home map and proceed to booking.',
    view_providers_for_service: 'View providers for this service',
    find_nearby_providers: 'Find nearby providers',
    // Edit Profile
    edit_profile: 'Edit Profile',
    avatar_url: 'Avatar URL',
    avatar_url_placeholder: 'https://example.com/your-photo.jpg',
    avatar_helper: 'Paste a direct image link or leave empty to use initials',
    full_name: 'Full Name',
    full_name_placeholder: 'Your full name',
    phone_placeholder: 'Your phone number',
    date_of_birth: 'Date of Birth',
    dob_placeholder: 'YYYY-MM-DD',
    dob_helper: 'Use ISO date format YYYY-MM-DD',
    gender: 'Gender',
    select_gender: 'Select gender',
    gender_male: 'Male',
    gender_female: 'Female',
    gender_other: 'Other',
    timezone: 'Timezone',
    timezone_placeholder: 'e.g. Africa/Casablanca',
    preferred_payment_method: 'Preferred Payment Method',
    select_payment_method: 'Select payment method',
    payment_cash: 'Cash',
    payment_card: 'Card',
    payment_mobile_money: 'Mobile Money',
    payment_wallet: 'Wallet',
    cancel: 'Cancel',
    profile_updated_title: 'Profile Updated',
    profile_updated_message: 'Your profile has been updated successfully.',
    something_went_wrong: 'Something went wrong. Please try again.',
    save: 'Save',
    your_profile: 'Your Profile',
    tap_to_change_photo: 'Tap to change photo',
    personal_information: 'Personal Information',
    additional_details: 'Additional Details',
    permission_required: 'Permission Required',
    camera_permission_message: 'We need access to your photo library to update your profile picture.',
    // Address Management
    add_new_address: 'Add New Address',
    no_addresses_saved: 'No addresses saved',
    add_frequently_used_addresses: 'Add your frequently used addresses for faster booking',
    add_your_first_address: 'Add Your First Address',
    default: 'Default',
    edit_address: 'Edit Address',
    delete_address: 'Delete Address',
    set_as_default: 'Set as Default',
    choose_an_action: 'Choose an action',
    are_you_sure_delete_address: 'Are you sure you want to delete {label}?',
    edit_functionality_coming_soon: 'Edit functionality for {label} will be available soon.',
    // Add Address
    add_address: 'Add Address',
    address_label: 'Address Label',
    address_label_placeholder: 'e.g. Home, Office, Gym',
    full_address: 'Full Address',
    full_address_placeholder: 'Enter complete address',
    address_type: 'Address Type',
    address_home: 'Home',
    address_work: 'Work',
    address_other: 'Other',
    set_as_default_address: 'Set as default address',
    address_added_successfully: 'Address added successfully',
    // Support & Legal
    support_legal_title: 'Support & Legal',
    contact_support: 'Contact Support',
    get_help_with_your_account: 'Get help with your account or services',
    privacy_policy: 'Privacy Policy',
    read_our_privacy_policy: 'Read our privacy policy',
    terms_of_service: 'Terms of Service',
    view_terms_and_conditions: 'View terms and conditions',
    about_app: 'About App',
    learn_more_about_app: 'Learn more about our app',
    // Help Center
    help_center_title: 'Help Center',
    frequently_asked_questions: 'Frequently Asked Questions',
    find_answers_to_common_questions: 'Find answers to common questions',
    contact_us: 'Contact Us',
    get_in_touch_with_support: 'Get in touch with our support team',
    report_issue: 'Report an Issue',
    report_bug_or_problem: 'Report a bug or problem',
    // Service Providers
    service_providers: 'Service Providers',
    available_workers: 'Available Workers',
    find_nearby_service_providers: 'Find nearby service providers',
    // Worker Profile
    worker_profile: 'Worker Profile',
    about_worker: 'About {name}',
    services_offered: 'Services Offered',
    reviews_and_ratings: 'Reviews & Ratings',
    contact_worker: 'Contact Worker',
    // Additional Address keys
    validation_error: 'Validation Error',
    address_label_required: 'Address label is required',
    address_required: 'Address is required',
    address_saved: 'Address Saved',
    address_saved_message: 'Your address has been saved successfully',
    failed_to_save_address: 'Failed to save address. Please try again.',
    location_permission_message: 'Location permission is required to use current location',
    location_found: 'Location Found',
    location_auto_filled: 'Address fields have been auto-filled with your current location',
    location_error: 'Location Error',
    unable_to_get_address: 'Unable to get address from current location',
    failed_to_get_location: 'Failed to get current location. Please try again.',
    location_services: 'Location Services',
    getting_location: 'Getting Location...',
    use_current_location: 'Use Current Location',
    default_address_description: 'Use this address for future bookings by default',
    city: 'City',
    postal_code: 'Postal Code',
    // Help Center keys
    getting_started: 'Getting Started',
    how_to_book_service: 'How to book a car wash service',
    finding_right_washer: 'Finding the right car washer',
    understanding_pricing: 'Understanding pricing',
    payment_methods_help: 'Payment methods',
    managing_bookings: 'Managing Bookings',
    canceling_rescheduling: 'Canceling or rescheduling',
    tracking_booking: 'Tracking your booking',
    rating_reviews: 'Rating and reviews',
    booking_history: 'Booking history',
    account_settings: 'Account & Settings',
    help_creating_account: 'Creating an account',
    managing_profile: 'Managing your profile',
    notification_settings: 'Notification settings',
    privacy_security: 'Privacy and security',
    troubleshooting: 'Troubleshooting',
    app_not_working: 'App not working properly',
    payment_issues: 'Payment issues',
    worker_no_show: 'Worker didn\'t show up',
    quality_concerns: 'Quality concerns',
    live_chat: 'Live Chat',
    chat_with_support: 'Chat with our support team',
    call_us: 'Call Us',
    email_support: 'Email Support',
    emergency_contact: 'Emergency Contact',
    call_emergency_hotline: 'Call emergency hotline?',
    urgent_safety_concern: 'If you have an urgent safety concern or emergency, please contact us immediately.',
    emergency_hotline: 'Emergency Hotline',
    help_topic: 'Help Topic',
    information_about: 'Information about: {item}',
    feature_available_soon: 'This feature will be available soon with detailed help content.',
    chat_feature_soon: 'Chat feature will be available soon',
    // Worker Detail Screen
    experience: 'Experience',
    starting_price: 'Starting Price',
    schedule_later: 'Schedule Later',
    // Booking Services Screen
    select_services: 'Select Services',
    services_for_vehicle_type: 'Services for your vehicle',
    filtered_for_vehicle: 'Filtered',
    loading_services: 'Loading services...',
    error_loading_services: 'Error Loading Services',
    failed_to_load_services: 'Failed to load services. Please try again.',
    retry: 'Retry',
    no_services_selected: 'No Services Selected',
    please_select_at_least_one_service: 'Please select at least one service',
    selected_services: 'Selected Services',
    total_services: 'Total Services:',
    tap_to_add: 'Tap to add',
    tap_to_remove: 'Tap to remove',
    service_information: 'Service Information',
    all_services_include_professional: 'All services include professional equipment and eco-friendly products',
    service_duration_varies: 'Service duration varies based on selected services (30-90 minutes)',
    you_can_modify_selection: 'You can modify your selection before final confirmation',
    start_booking_process: 'Start Booking Process',
    // Booking Screen
    book_service_title: 'Book Service',
    loading_worker_details: 'Loading worker details...',
    worker_not_available_title: 'Worker Not Available',
    worker_no_longer_available: 'This worker is no longer available. Please select another worker.',
    welcome_guest_title: 'Welcome Guest',
    please_sign_in_to_continue: 'Please sign in to continue with your booking',
    sign_in_button: 'Sign In',
    professional_car_washer_role: 'Professional Car Washer',
    starting_price_label: 'Starting Price',
    what_to_expect_title: 'What to Expect',
    professional_mobile_car_wash: 'Professional mobile car wash service',
    we_bring_all_equipment: 'We bring all equipment and water',
    eco_friendly_products: 'Eco-friendly products used',
    satisfaction_guaranteed: 'Satisfaction guaranteed',
    booking_process_title: 'Booking Process',
    select_date_and_time: 'Select date and time',
    choose_vehicle_details: 'Choose vehicle details',
    select_services_you_want: 'Select services you want',
    provide_service_location: 'Provide service location',
    select_payment_and_confirm: 'Select payment and confirm',
    worker_not_found_alert: 'Worker Not Found',
    // Booking DateTime Screen
    select_date_time_title: 'Select Date & Time',
    step_1_of_6: 'Step 1 of 6',
    step_1_of_6_select_date_time: 'Step 1 of 6: Select Date & Time',
    select_date_label: 'Select Date',
    select_time_label: 'Select Time',
    missing_fields_alert: 'Missing Fields',
    please_select_date_and_time: 'Please select date and time',
    select_date_button: 'Select Date',
    today_label: 'Today',
    tomorrow_label: 'Tomorrow',
    morning_period: 'Morning',
    afternoon_period: 'Afternoon',
    evening_period: 'Evening',
    selected_appointment: 'Selected Appointment',
    cancel_button: 'Cancel',
    done_button: 'Done',
    // Booking Payment Screen
    payment_method_title: 'Payment Method',
    step_5_of_5: 'Step 5 of 5',
    step_5_of_5_payment_method: 'Step 5 of 5: Payment Method',
    select_payment_method_label: 'Select Payment Method',
    cash_on_delivery_title: 'Cash on Delivery',
    pay_with_cash_when_completed: 'Pay with cash when service is completed',
    credit_debit_card_title: 'Credit/Debit Card',
    pay_securely_with_card: 'Pay securely with your card',
    mobile_payment_title: 'Mobile Payment',
    pay_with_mobile_wallet: 'Pay with mobile wallet apps',
    digital_wallet_title: 'Digital Wallet',
    pay_with_digital_wallet: 'Pay with digital wallet services',
    recommended_badge: 'Recommended',
    coming_soon_text: 'Coming Soon',
    payment_due_after_completion: 'Payment due after service completion',
    exact_change_appreciated: 'Exact change appreciated',
    receipt_will_be_provided: 'Receipt will be provided',
    payment_summary_title: 'Payment Summary',
    pay_after_service_completion: 'Pay after service completion',
    vehicle_type_label: 'Vehicle Type',
    total_amount_label: 'Total Amount:',
    amount_to_be_paid_cash: 'Amount to be paid in cash after service',
    secure_payment_processing: 'Secure payment processing',
    payment_information_title: 'Payment Information',
    all_transactions_secure: 'All transactions are secure',
    no_payment_required_now: 'No payment required now',
    no_hidden_fees: 'No hidden fees or charges',
    authentication_required_alert: 'Authentication Required',
    please_sign_in_to_create_booking: 'Please sign in to create a booking',
    missing_information_alert: 'Missing Information',
    please_complete_all_steps: 'Please complete all booking steps. Missing:',
    booking_failed_alert: 'Booking Failed',
    failed_to_create_booking: 'Failed to create booking. Please try again.',
    // Booking Confirmation Screen
    booking_confirmed_title: 'Booking Confirmed!',
    car_wash_service_booked: 'Your car wash service has been successfully booked',
    booking_id_label: 'Booking ID',
    my_bookings_button: 'My Bookings',
    go_home_button: 'Go Home',
    // Booking Location Screen
    service_location_title: 'Service Location',
    step_4_of_5: 'Step 4 of 5',
    step_4_of_5_service_location: 'Step 4 of 5: Service Location',
    quick_select_label: 'Quick Select',
    current_location_title: 'Current Location',
    use_my_current_location: 'Use my current location',
    saved_address_title: 'Saved Address',
    service_address_label: 'Service Address',
    enter_your_full_address: 'Enter your full address',
    include_building_number: 'Include building number, street, and area',
    service_information_title: 'Service Information',
    worker_will_arrive_scheduled: 'Worker will arrive at your scheduled time',
    service_typically_takes: 'Service typically takes 30-60 minutes',
    all_water_equipment_provided: 'All water and equipment provided',
    missing_fields_location: 'Missing Fields',
    please_enter_service_address: 'Please enter service address',
    // Booking Vehicle Screen
    vehicle_details_title: 'Vehicle Details',
    step_3_of_5: 'Step 3 of 5',
    step_3_of_5_vehicle_details: 'Step 3 of 5: Vehicle Details',
    car_label: 'Car',
    motor_label: 'Motor',
    motor_type_label: 'Motor Type',
    car_brand_label: 'Car Brand',
    car_model_label: 'Car Model',
    year_label: 'Year',
    show_all_brands: 'Show All Brands',
    search_brands: 'Search brands...',
    select_brand_first: 'Select brand first',
    select_year: 'Select year',
    vehicle_information_title: 'Vehicle Information',
    accurate_details_better_service: 'Accurate vehicle details help us provide better service',
    pricing_may_vary_by_size: 'Pricing may vary based on vehicle size and type',
    all_vehicle_types_welcome: 'All vehicle types are welcome',
    please_select_vehicle_type: 'Please select vehicle type',
    loading: 'Loading',
    loading_models: 'Loading models',
    loading_brands: 'Loading brands',
    popular_brands: 'Popular Brands',
    no_brands_found: 'No brands found matching',
    selected_vehicle: 'Selected Vehicle:',
    // Vehicle Information
    vehicle_info_card_title: 'Vehicle Information',
    accurate_vehicle_details: 'Accurate vehicle details help us provide better service',
    pricing_varies_by_vehicle: 'Pricing may vary based on vehicle size and type',
    all_vehicles_welcome: 'All vehicle types are welcome',
    // Service Workers Screen
    providers: 'Providers',
    loading_workers: 'Loading workers...',
    error_loading_workers: 'Error Loading Workers',
    failed_to_load_workers: 'Failed to load workers. Please try again.',
    no_providers_found: 'No providers found for this service',
    try_checking_back_later: 'Try checking back later or select a different service',
    refresh: 'Refresh',
    reviews: 'reviews',
    years_exp: 'years exp',
    available: 'Available',
    busy: 'Busy',
    services_label: 'Services:',
    service_not_loaded_properly: 'Service not loaded properly. Please try again.',
    // Worker Dashboard Screen
    welcome_back_worker: 'Welcome back',
    dashboard_overview: 'Here\'s your dashboard overview',
    todays_earnings: 'Today\'s Earnings',
    this_week: 'This Week',
    rating: 'Rating',
    loading_bookings: 'Loading bookings...',
    manage_bookings: 'Manage Bookings',
    view_manage_all_bookings: 'View and manage all your bookings',
    recent_activity: 'Recent Activity',
    view_all: 'View All',
    accept_booking: 'Accept Booking',
    accept_booking_confirm: 'Are you sure you want to accept this booking?',
    accept: 'Accept',
    success: 'Success',
    booking_accepted: 'Booking accepted!',
    failed_accept_booking: 'Failed to accept booking',
    reject_booking: 'Reject Booking',
    reject_booking_confirm: 'Are you sure you want to reject this booking?',
    reject: 'Reject',
    rejected: 'Rejected',
    booking_rejected: 'Booking rejected.',
    failed_reject_booking: 'Failed to reject booking',
    complete_booking: 'Complete Booking',
    complete_booking_confirm: 'Mark this booking as completed?',
    complete: 'Complete',
    booking_completed: 'Booking completed!',
    failed_complete_booking: 'Failed to complete booking',
    start_booking: 'Start Booking',
    start_booking_confirm: 'Mark this booking as in progress?',
    start: 'Start',
    booking_started: 'Booking started!',
    failed_start_booking: 'Failed to start booking',
    completed: 'Completed',
    customer_contact_info: 'Customer contact info',
    rating_stars: 'stars',
    mark_complete: 'Mark Complete',
    user_not_authenticated: 'User not authenticated',
    failed_load_worker_data: 'Failed to load worker data',
    // Worker Bookings Screen
    failed_load_bookings: 'Failed to load bookings',
    unavailable: 'Unavailable',
    customer_phone_not_available: 'Customer phone number not available.',
    unable_to_open_phone_app: 'Unable to open the phone app.',
    booking_accepted_successfully: 'Booking accepted successfully!',
    failed_accept_booking_short: 'Failed to accept booking',
    notice: 'Notice',
    booking_marked_completed: 'Booking marked as completed!',
    failed_complete_booking_short: 'Failed to complete booking',
    pending: 'Pending',
    active: 'Active',
    in_progress: 'In Progress',
    contact_customer: 'Contact Customer',
    customer_rating: 'Customer rating',
    no_bookings: 'No {status} bookings',
    new_booking_requests_appear: 'New booking requests will appear here',
    accepted_bookings_show: 'Accepted bookings will show here',
    completed_jobs_listed: 'Your completed jobs will be listed here',
    // Vehicle Types
    vehicle_type_sedan: 'Sedan',
    vehicle_type_compact: 'Compact',
    vehicle_type_medium_suv: 'Medium SUV',
    vehicle_type_large_suv: 'Large SUV',
    vehicle_type_motorcycle: 'Motorcycle',
    // Services Screen
    please_select_vehicle_type_to_see_services: 'Please select a vehicle type to see available services',
    no_services_available_for_vehicle_type: 'No services available for this vehicle type',
    price: 'Price',
    duration: 'Duration',
    no_inclusions_available: 'No inclusions information available',
    book_this_service: 'Book This Service',
    // Entry Screen Bubbles
    map: 'Map',
    entry_basic_title: 'Basic Wash',
    entry_deluxe_title: 'Deluxe Wash',
    entry_deep_title: 'Deep Clean',
    entry_pro_title: 'Pro Package',
    entry_express_title: 'Express Service',
    entry_protection_title: 'Paint Protection',
    // Change Information
    customer_change: 'Customer has',
    change: 'change',
    // Phone Number Required Modal
    phone_number_required: 'Phone Number Required',
    phone_number_required_message: 'A phone number is required to complete your booking. Please enter your phone number below.',
    enter_phone_number_placeholder: '+212 6XX XXX XXX',
    save_phone_number: 'Save & Continue',
    invalid_phone_number: 'Invalid Phone Number',
    invalid_phone_number_message: 'Please enter a valid phone number.',
    phone_save_failed: 'Failed to save phone number. Please try again.',
    // Missing keys used across screens
    address: 'Address',
    and: 'and',
    arrival_confirmed: 'Arrival Confirmed',
    arrived_at_location: 'Arrived at location',
    at_point: 'at',
    available_services: 'Available Services',
    booking_rescheduled_and_accepted: 'Booking rescheduled and accepted',
    call_failed: 'Call Failed',
    confirm: 'Confirm',
    confirm_arrival: 'Confirm Arrival',
    continue_with_google: 'Continue with Google',
    copy_number: 'Copy Number',
    create_new_password: 'Create New Password',
    enter_new_password: 'Enter new password',
    enter_valid_phone_number: 'Please enter a valid phone number',
    error_loading_worker: 'Error loading worker details',
    loading_reviews: 'Loading reviews...',
    location_required: 'Location is required',
    new_password: 'New Password',
    new_password_instructions: 'Enter your new password below',
    no_phone: 'No phone number available',
    no_results_found: 'No results found',
    no_reviews_yet: 'No reviews yet',
    no_services_available: 'No services available',
    ok: 'OK',
    open_from_email_link: 'Please open this page from the link in your email',
    or: 'or',
    overall_rating: 'Overall Rating',
    password_too_short: 'Password must be at least 6 characters',
    password_update_failed: 'Failed to update password',
    password_update_success: 'Password Updated',
    password_updated: 'Your password has been updated successfully',
    passwords_dnot_match: 'Passwords do not match',
    phone_not_available: 'Phone number not available',
    phone_number_required_for_booking: 'Required to contact you about your booking',
    please_select_address_or_use_map: 'Please select an address or use the map',
    please_select_vehicle_type_first: 'Please select a vehicle type first',
    popular_services: 'Popular Services',
    reenter_new_password: 'Re-enter new password',
    reset_failed: 'Reset Failed',
    reset_instructions_sent: 'Reset instructions have been sent to your email',
    reset_sent: 'Reset Sent',
    reviewed: 'Reviewed',
    saving: 'Saving...',
    select_model: 'Select model',
    selected_service_not_found: 'Selected service not found',
    sending: 'Sending...',
    service_details: 'Service Details',
    session_not_ready: 'Session not ready. Please try again.',
    set_new_password: 'Set New Password',
    specialties: 'Specialties',
    step_3_of_5_select_services: 'Step 3 of 5: Select Services',
    tap_to_select: 'Tap to select',
    type_message: 'Type a message...',
    update_password: 'Update Password',
    failed_mark_arrival: 'Failed to mark arrival',
    failed_reschedule_accept: 'Failed to reschedule and accept',
    // ChangePasswordScreen
    update_your_password: 'Update your password',
    enter_current_and_new: 'Enter your current password and your new password.',
    current_password: 'Current Password',
    enter_current_password: 'Enter current password',
    confirm_new_password: 'Confirm New Password',
    confirm_new_password_placeholder: 'Confirm new password',
    updating: 'Updating...',
    password_changed: 'Password Changed',
    password_changed_message: 'Your password has been successfully updated. You will be redirected to the login screen to sign in with your new password.',
    go_to_login: 'Go to Login',
    // ForgotPasswordScreen
    please_wait: 'Please Wait',
    too_many_requests: 'Too Many Requests',
    // ManageBookingScreen
    manage_booking: 'Manage Booking',
    // AddressScreens
    // BookingReviewScreen
    review_booking: 'Review Booking',
    // NotificationsScreen
    booking_confirmed_notif: 'Booking Confirmed',
    booking_completed_notif: 'Booking Completed',
    promo: 'Promo',
    support_notif: 'Support',
    // ProfileScreen
    copy_token: 'Copy Token',
    // ResetPasswordScreen
    session_expired: 'Session Expired',
    // ForgotPasswordScreen
    reset_password: 'Reset Password',
    reset_instructions: 'Enter your email and we\'ll send you instructions to reset your password',
    reset_method: 'Reset Method',
    email_address: 'Email Address',
    send_reset_instructions: 'Send Reset Instructions',
    back_to_sign_in: 'Back to Sign In',
    rate_limit_message: 'Rate limit reached. Please wait a few minutes before trying again.',
  },
  fr: {
    settings: 'Paramètres',
    home: 'Accueil',
    messaging: 'Messagerie',
    store: 'Boutique',
    dashboard: 'Tableau de bord',
    menu: 'Menu',
    account: 'Compte',
    preferences: 'Préférences',
    support_legal: 'Support & Légal',
    language: 'Langue',
    theme: 'Thème',
    help_center: 'Centre d\'aide',
    choose_language: 'Choisissez votre langue préférée',
    english: 'Anglais',
    french: 'Français',
    save_changes: 'Enregistrer les modifications',
    confirm_booking: 'Confirmer la réservation',
    update_personal_info: 'Mettre à jour vos informations personnelles',
    manage_addresses: 'Gérer les adresses',
    add_edit_locations: 'Ajouter ou modifier vos lieux enregistrés',
    payment_methods: 'Moyens de paiement',
    manage_payment_options: 'Gérer vos options de paiement',
    choose_app_appearance: 'Choisissez l\'apparence de l\'application',
    help_privacy_terms_about: 'Aide, Confidentialité, Conditions, À propos',
    select_date: 'Sélectionner une date',
    back: 'Retour',
    is_coming_soon: 'arrive bientôt',
    we_are_working_to_bring: 'Nous travaillons dur pour vous apporter',
    to_you_stay_tuned: 'bientôt. Restez à l\'écoute !',
    close: 'Fermer',
    search_placeholder: 'Rechercher des services de lavage auto…',
    book_now: 'Réserver',
    book: 'Réserver',
    km_away: 'km',
    location_permission: 'Autorisation de localisation',
    permission_denied_msg: 'Permission refusée. Utilisation du centre-ville par défaut.',
    profile: 'Profil',
    welcome_guest: 'Bienvenue, Invité !\n',
    guest_prompt: 'Connectez-vous ou créez un compte pour accéder à votre profil et à votre historique de réservations',
    sign_in: 'Se connecter',
    create_account: 'Créer un compte',
    continue_as_guest: 'Continuer en tant qu\'invité',
    service_provider: 'Prestataire',
    customer: 'Client',
    member_since: 'Membre depuis',
    your_stats: 'Vos statistiques',
    rating_label: 'Note',
    jobs_done: 'Travaux effectués',
    contact_information: 'Informations de contact',
    email: 'E-mail',
    phone: 'Téléphone',
    location: 'Emplacement',
    account_label: 'Compte',
    change_password: 'Changer le mot de passe',
    worker_dashboard: 'Tableau de bord prestataire',
    sign_out: ' déconnecter',
    sign_out_confirm_title: 'Déconnexion',
    sign_out_confirm_message: 'Êtes-vous sûr de vouloir vous déconnecter ?',
    error: 'Erreur',
    failed_sign_out: 'Échec de la déconnexion. Veuillez réessayer.',
    recently: 'Récemment',
    date: 'Date',
    time: 'Heure',
    enter_your_address: 'Entrez votre adresse',
    the_worker_will_come_to_this_location_to_wash_your_car: "Le prestataire viendra à cet endroit pour nettoyer votre voiture",
    select_time: 'Sélectionner une heure',
    select_vehicle_type: 'Sélectionner un type de véhicule',
    any_special_instructions_or_requests: 'Des instructions ou demandes particulières ?',
    missing_fields: 'Champs manquants',
    please_complete: 'Veuillez compléter',
    worker_not_found: 'Prestataire introuvable',
    please_select_worker_again: 'Veuillez revenir en arrière et sélectionner un prestataire à nouveau.',
    // Booking Confirmation
    booking_confirmed: 'Réservation confirmée !',
    scheduled_message: 'Votre lavage de voiture a été planifié',
    booking_id: 'ID de réservation',
    your_car_washer: 'Votre laveur de voitures',
    professional_car_washer: 'Laveur de voitures professionnel',
    confirmed: 'Confirmée',
    booking_details: 'Détails de la réservation',
    service_location: 'Lieu du service',
    date_time: 'Date et heure',
    at: 'à',
    vehicle_type: 'Type de véhicule',
    payment_method: 'Moyen de paiement',
    cash_on_delivery: 'Paiement à la livraison',
    additional_notes: 'Notes supplémentaires',
    total_amount: 'Montant total',
    to_be_paid_upon_completion: 'À payer à la fin du service',
    important_information: 'Informations importantes',
    info_line_1: '• Le laveur arrivera 5 à 10 minutes avant l\'heure prévue',
    info_line_2: '• Assurez-vous qu\'un accès à l\'eau est disponible sur place',
    info_line_3: '• Le paiement est dû à la fin du service',
    info_line_4: '• Vous pouvez contacter le laveur directement si nécessaire',
    view_my_bookings: 'Voir mes réservations',
    back_to_home: 'Retour à l\'accueil',
    // Bookings screen
    my_bookings: 'Mes réservations',
    tab_all: 'Tout',
    tab_upcoming: 'À venir',
    tab_active: 'En cours',
    tab_completed: 'Terminées',
    no_bookings_found: 'Aucune réservation trouvée',
    no_bookings_yet: "Vous n\'avez pas encore effectué de réservation",
    no_status_bookings: 'Aucune réservation {status} pour le moment',
    book_a_service: 'Réserver un service',
    booked_on: 'Réservé le',
    call: 'Appeler',
    chat: 'Discuter',
    rate_service: 'Évaluer le service',
    status_pending: 'En attente',
    status_confirmed: 'Confirmée',
    status_in_progress: 'En cours',
    status_completed: 'Terminée',
    status_cancelled: 'Annulée',
    // Review Screen
    how_was_service: 'Comment était votre service ?',
    tap_stars_to_rate: 'Appuyez sur les étoiles pour évaluer votre expérience',
    excellent: 'Excellent !',
    very_good: 'Très bien !',
    good: 'Bien',
    fair: 'Passable',
    poor: 'Médiocre',
    what_went_well: 'Qu\'est-ce qui s\'est bien passé ?',
    what_went_wrong: 'Qu\'est-ce qui n\'a pas fonctionné ?',
    select_all_apply: 'Sélectionnez tout ce qui s\'applique (optionnel)',
    write_review: 'Écrire un avis',
    share_experience: 'Partagez-en plus sur votre expérience (optionnel)',
    review_placeholder: 'Parlez-nous de votre expérience...',
    characters: 'caractères',
    review_tips: 'Conseils pour l\'avis',
    tip_specific: 'Soyez précis sur ce que vous avez aimé ou pas',
    tip_constructive: 'Gardez vos commentaires constructifs et respectueux',
    tip_helpful: 'Votre avis aide les autres à prendre des décisions éclairées',
    submitting: 'Envoi en cours...',
    submit_review: 'Soumettre l\'avis',
    review_submitted: 'Avis soumis',
    thank_you_feedback: 'Merci pour votre retour !',
    booking: 'Réservation',
    // Review Tags - Positive
    tag_professional: 'Professionnel',
    tag_on_time: 'À l\'heure',
    tag_thorough: 'Minutieux',
    tag_friendly: 'Sympathique',
    tag_quality: 'Excellente qualité',
    tag_value: 'Bon rapport qualité-prix',
    // Review Tags - Negative
    tag_late: 'Arrivée tardive',
    tag_rushed: 'Travail bâclé',
    tag_incomplete: 'Incomplet',
    tag_unprofessional: 'Peu professionnel',
    tag_expensive: 'Trop cher',
    tag_damage: 'A causé des dommages',
    // Login Screen
    welcome_back: 'Bienvenue',
    sign_in_to_book: 'Connectez-vous pour réserver votre service de lavage auto',
    enter_your_email: 'Entrez votre email',
    enter_your_password: 'Entrez votre mot de passe',
    password: 'Mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    forgot_password: 'Mot de passe oublié ?',
    signing_in: 'Connexion en cours...',
    dont_have_account: "Vous n'avez pas de compte ?",
    sign_up: 'S\'inscrire',
    login_failed: 'Échec de la connexion',
    check_credentials: 'Veuillez vérifier vos identifiants et réessayer.',
    // Signup Screen
    join_us_to_book: 'Rejoignez-nous pour réserver des services professionnels de lavage auto',
    enter_full_name: 'Entrez votre nom complet',
    enter_email: 'Entrez votre email',
    phone_number: 'Numéro de téléphone',
    enter_phone_number: 'Entrez votre numéro de téléphone',
    create_password: 'Créez un mot de passe',
    confirm_your_password: 'Confirmez votre mot de passe',
    please_confirm_password: 'Veuillez confirmer votre mot de passe',
    i_agree_to: 'J\'accepte les',
    creating_account: 'Création du compte...',
    already_have_account: 'Vous avez déjà un compte ?',
    passwords_dont_match: 'Les mots de passe ne correspondent pas',
    passwords_must_match: 'Veuillez vous assurer que les deux mots de passe sont identiques.',
    terms_not_accepted: 'Conditions non acceptées',
    agree_to_terms: 'Veuillez accepter les conditions générales pour continuer.',
    signup_failed: 'Échec de l\'inscription',
    verify_your_email: 'Vérifiez votre email',
    verification_email_sent: 'Nous avons envoyé un lien de vérification à {email}.\\nOuvrez votre email, confirmez votre compte, puis connectez-vous.',
    email_already_registered: 'Cet email est déjà enregistré. Veuillez vous connecter ou utiliser un autre email.',
    invalid_email: 'Veuillez entrer une adresse email valide.',
    weak_password: 'Votre mot de passe ne répond pas aux exigences.',
    // Services
    services_title: 'Services',
    services_subtitle: 'Choisissez un service adapté à votre voiture',
    view_details: 'Voir les détails',
    service_basic_title: 'Lavage basique',
    service_basic_desc: 'Lavage extérieur et séchage',
    service_deluxe_title: 'Lavage deluxe',
    service_deluxe_desc: 'Nettoyage extérieur + intérieur',
    service_deep_title: 'Nettoyage en profondeur',
    service_deep_desc: 'Détail complet intérieur/extérieur',
    service_interior_title: 'Détail intérieur',
    service_interior_desc: 'Aspiration et nettoyage intérieur',
    service_pro_title: 'Pack Pro',
    service_pro_desc: 'Rinçage, cire et polissage',
    // Service Detail
    service_not_found: 'Service introuvable.',
    go_back: 'Retour',
    whats_included: 'Ce qui est inclus',
    include_line_1: '• Rinçage haute pression',
    include_line_2: '• Shampoing au pH neutre',
    include_line_3: '• Lavage et séchage à la microfibre',
    include_line_4: '• Nettoyage des vitres et miroirs',
    include_line_5: '• Brillance des pneus et finition extérieure',
    notes: 'Notes',
    notes_body: 'La durée dépend de la taille et de l’état du véhicule. Les prix peuvent varier selon le prestataire. Vous pouvez sélectionner un travailleur depuis la carte d’accueil et procéder à la réservation.',
    view_providers_for_service: 'Voir les prestataires',
    find_nearby_providers: 'Pros proches',
    avatar_url: 'URL de l’avatar',
    avatar_url_placeholder: 'https://exemple.com/votre-photo.jpg',
    avatar_helper: 'Collez un lien d’image direct ou laissez vide pour utiliser les initiales',
    full_name: 'Nom complet',
    full_name_placeholder: 'Votre nom complet',
    phone_placeholder: 'Votre numéro de téléphone',
    date_of_birth: 'Date de naissance',
    dob_placeholder: 'AAAA-MM-JJ',
    dob_helper: 'Utilisez le format ISO AAAA-MM-JJ',
    gender: 'Genre',
    select_gender: 'Sélectionner le genre',
    gender_male: 'Homme',
    gender_female: 'Femme',
    gender_other: 'Autre',
    timezone: 'Fuseau horaire',
    timezone_placeholder: 'ex. Africa/Casablanca',
    preferred_payment_method: 'Mode de paiement préféré',
    select_payment_method: 'Sélectionner un mode de paiement',
    payment_cash: 'Espèces',
    payment_card: 'Carte',
    payment_mobile_money: 'Mobile Money',
    payment_wallet: 'Portefeuille',
    cancel: 'Annuler',
    profile_updated_title: 'Profil mis à jour',
    profile_updated_message: 'Votre profil a été mis à jour avec succès.',
    something_went_wrong: 'Une erreur est survenue. Veuillez réessayer.',
    save: 'Enregistrer',
    your_profile: 'Votre Profil',
    tap_to_change_photo: 'Appuyez pour changer la photo',
    personal_information: 'Informations personnelles',
    additional_details: 'Détails supplémentaires',
    permission_required: 'Autorisation requise',
    camera_permission_message: 'Nous avons besoin d\'accéder à votre photothèque pour mettre à jour votre photo de profil.',
    // Address Management
    add_new_address: 'Ajouter une nouvelle adresse',
    no_addresses_saved: 'Aucune adresse enregistrée',
    add_frequently_used_addresses: 'Ajoutez vos adresses fréquemment utilisées pour une réservation plus rapide',
    add_your_first_address: 'Ajoutez votre première adresse',
    default: 'Par défaut',
    edit_address: 'Modifier l\'adresse',
    delete_address: 'Supprimer l\'adresse',
    set_as_default: 'Définir par défaut',
    choose_an_action: 'Choisissez une action',
    are_you_sure_delete_address: 'Êtes-vous sûr de vouloir supprimer {label} ?',
    edit_functionality_coming_soon: 'La fonctionnalité de modification pour {label} sera bientôt disponible.',
    // Add Address
    add_address: 'Ajouter une adresse',
    address_label: 'Libellé de l\'adresse',
    address_label_placeholder: 'ex. Maison, Bureau, Salle de sport',
    full_address: 'Adresse complète',
    full_address_placeholder: 'Entrez l\'adresse complète',
    address_type: 'Type d\'adresse',
    address_home: 'Maison',
    address_work: 'Travail',
    address_other: 'Autre',
    set_as_default_address: 'Définir comme défaut',
    address_added_successfully: 'Adresse ajoutée avec succès',
    location_services: 'Services de localisation',
    getting_location: 'Obtention de la localisation...',
    use_current_location: 'Utiliser la position actuelle',
    default_address_description: 'Utiliser cette adresse pour les futures réservations par défaut',
    location_error: 'Erreur de localisation',
    unable_to_get_address: 'Impossible d\'obtenir l\'adresse à partir de la position actuelle',
    failed_to_get_location: 'Échec de l\'obtention de la position actuelle. Veuillez réessayer.',
    location_found: 'Position trouvée',
    location_auto_filled: 'Les champs d\'adresse ont été remplis automatiquement avec votre position actuelle',
    location_permission_message: 'L\'autorisation de localisation est requise pour utiliser la position actuelle',
    city: 'Ville',
    postal_code: 'Code postal',
    // Support & Legal
    support_legal_title: 'Support et Légal',
    contact_support: 'Contacter le support',
    get_help_with_your_account: 'Obtenez de l\'aide avec votre compte ou vos services',
    privacy_policy: 'Politique de confidentialité',
    read_our_privacy_policy: 'Lisez notre politique de confidentialité',
    terms_of_service: 'Conditions d\'utilisation',
    view_terms_and_conditions: 'Voir les termes et conditions',
    about_app: 'À propos de l\'app',
    learn_more_about_app: 'En savoir plus sur notre application',
    // Help Center
    help_center_title: 'Centre d\'aide',
    frequently_asked_questions: 'Questions fréquemment posées',
    find_answers_to_common_questions: 'Trouvez des réponses aux questions courantes',
    contact_us: 'Nous contacter',
    get_in_touch_with_support: 'Contactez notre équipe de support',
    report_issue: 'Signaler un problème',
    report_bug_or_problem: 'Signaler un bug ou un problème',
    // Service Providers
    service_providers: 'Prestataires de services',
    available_workers: 'Travailleurs disponibles',
    find_nearby_service_providers: 'Trouvez des prestataires de services à proximité',
    // Worker Profile
    worker_profile: 'Profil du travailleur',
    about_worker: 'À propos de {name}',
    services_offered: 'Services offerts',
    reviews_and_ratings: 'Avis et évaluations',
    contact_worker: 'Contacter le travailleur',
    // Worker Detail Screen
    experience: 'Expérience',
    starting_price: 'Prix de départ',
    schedule_later: 'Programmer plus tard',
    // Booking Services Screen
    select_services: 'Sélectionner les services',
    services_for_vehicle_type: 'Services pour votre véhicule',
    filtered_for_vehicle: 'Filtré',
    loading_services: 'Chargement des services...',
    error_loading_services: 'Erreur de chargement des services',
    failed_to_load_services: 'Échec du chargement des services. Veuillez réessayer.',
    retry: 'Réessayer',
    no_services_selected: 'Aucun service sélectionné',
    please_select_at_least_one_service: 'Veuillez sélectionner au moins un service',
    selected_services: 'Services sélectionnés',
    total_services: 'Total des services :',
    tap_to_add: 'Appuyez pour ajouter',
    tap_to_remove: 'Appuyez pour retirer',
    service_information: 'Informations sur le service',
    all_services_include_professional: 'Tous les services incluent un équipement professionnel et des produits écologiques',
    service_duration_varies: 'La durée du service varie selon les services sélectionnés (30-90 minutes)',
    you_can_modify_selection: 'Vous pouvez modifier votre sélection avant la confirmation finale',
    start_booking_process: 'Commencer ',
    // Booking Screen
    book_service_title: 'Réserver un service',
    loading_worker_details: 'Chargement des détails du travailleur...',
    worker_not_available_title: 'Travailleur non disponible',
    worker_no_longer_available: 'Ce travailleur n\'est plus disponible. Veuillez sélectionner un autre travailleur.',
    welcome_guest_title: 'Bienvenue, Invité',
    please_sign_in_to_continue: 'Veuillez vous connecter pour continuer votre réservation',
    sign_in_button: 'Se connecter',
    professional_car_washer_role: 'Laveur de voitures professionnel',
    starting_price_label: 'Prix de départ',
    what_to_expect_title: 'À quoi s\'attendre',
    professional_mobile_car_wash: 'Service de lavage mobile professionnel',
    we_bring_all_equipment: 'Nous apportons tout l\'équipement et l\'eau',
    eco_friendly_products: 'Produits écologiques utilisés',
    satisfaction_guaranteed: 'Satisfaction garantie',
    booking_process_title: 'Processus de réservation',
    select_date_and_time: 'Sélectionner la date et l\'heure',
    choose_vehicle_details: 'Choisir les détails du véhicule',
    select_services_you_want: 'Sélectionner les services désirés',
    provide_service_location: 'Fournir l\'emplacement du service',
    select_payment_and_confirm: 'Sélectionner le paiement et confirmer',
    worker_not_found_alert: 'Travailleur introuvable',
    // Booking DateTime Screen
    select_date_time_title: 'Sélectionner date et heure',
    step_1_of_6: 'Étape 1 sur 6',
    step_1_of_6_select_date_time: 'Étape 1 sur 6 : Sélectionner date et heure',
    select_date_label: 'Sélectionner une date',
    select_time_label: 'Sélectionner l\'heure',
    missing_fields_alert: 'Champs manquants',
    please_select_date_and_time: 'Veuillez sélectionner la date et l\'heure',
    select_date_button: 'Sélectionner une date',
    today_label: 'Aujourd\'hui',
    tomorrow_label: 'Demain',
    morning_period: 'Matin',
    afternoon_period: 'Après-midi',
    evening_period: 'Soir',
    selected_appointment: 'Rendez-vous sélectionné',
    cancel_button: 'Annuler',
    done_button: 'Terminé',
    // Booking Payment Screen
    payment_method_title: 'Mode de paiement',
    step_5_of_5: 'Étape 5 sur 5',
    step_5_of_5_payment_method: 'Étape 5 sur 5 : Mode de paiement',
    select_payment_method_label: 'Sélectionner le mode de paiement',
    cash_on_delivery_title: 'Paiement à la livraison',
    pay_with_cash_when_completed: 'Payer en espèces à la fin du service',
    credit_debit_card_title: 'Carte de crédit/débit',
    pay_securely_with_card: 'Payer en toute sécurité avec votre carte',
    mobile_payment_title: 'Paiement mobile',
    pay_with_mobile_wallet: 'Payer avec des applications de portefeuille mobile',
    digital_wallet_title: 'Portefeuille numérique',
    pay_with_digital_wallet: 'Payer avec des services de portefeuille numérique',
    recommended_badge: 'Recommandé',
    coming_soon_text: 'Bientôt disponible',
    payment_due_after_completion: 'Paiement dû après la fin du service',
    exact_change_appreciated: 'Monnaie exacte appréciée',
    receipt_will_be_provided: 'Un reçu sera fourni',
    payment_summary_title: 'Résumé du paiement',
    pay_after_service_completion: 'Payer après la fin du service',
    vehicle_type_label: 'Type de véhicule',
    total_amount_label: 'Montant total :',
    amount_to_be_paid_cash: 'Montant à payer en espèces après le service',
    secure_payment_processing: 'Traitement de paiement sécurisé',
    payment_information_title: 'Informations de paiement',
    all_transactions_secure: 'Toutes les transactions sont sécurisées',
    no_payment_required_now: 'Aucun paiement requis maintenant',
    no_hidden_fees: 'Aucuns frais cachés',
    authentication_required_alert: 'Authentification requise',
    please_sign_in_to_create_booking: 'Veuillez vous connecter pour créer une réservation',
    missing_information_alert: 'Informations manquantes',
    please_complete_all_steps: 'Veuillez compléter toutes les étapes de réservation. Manquant :',
    booking_failed_alert: 'Échec de la réservation',
    failed_to_create_booking: 'Échec de la création de la réservation. Veuillez réessayer.',
    // Booking Confirmation Screen
    booking_confirmed_title: 'Réservation confirmée !',
    car_wash_service_booked: 'Votre service de lavage auto a été réservé avec succès',
    booking_id_label: 'ID de réservation',
    my_bookings_button: 'Mes réservations',
    go_home_button: 'Accueil',
    // Booking Location Screen
    service_location_title: 'Lieu de service',
    step_4_of_5: 'Étape 4 sur 5',
    step_4_of_5_service_location: 'Étape 4 sur 5 : Lieu de service',
    quick_select_label: 'Sélection rapide',
    current_location_title: 'Position actuelle',
    use_my_current_location: 'Utiliser ma position actuelle',
    saved_address_title: 'Adresse enregistrée',
    service_address_label: 'Adresse de service',
    enter_your_full_address: 'Entrez votre adresse complète',
    include_building_number: 'Inclure le numéro de bâtiment, la rue et la zone',
    service_information_title: 'Informations sur le service',
    worker_will_arrive_scheduled: 'Le travailleur arrivera à l\'heure prévue',
    service_typically_takes: 'Le service prend généralement 30-60 minutes',
    all_water_equipment_provided: 'Toute l\'eau et l\'équipement fournis',
    missing_fields_location: 'Champs manquants',
    please_enter_service_address: 'Veuillez entrer l\'adresse de service',
    // Booking Vehicle Screen
    vehicle_details_title: 'Détails du véhicule',
    step_3_of_5: 'Étape 3 sur 5',
    step_3_of_5_vehicle_details: 'Étape 3 sur 5 : Détails du véhicule',
    car_label: 'Voiture',
    motor_label: 'Moto',
    motor_type_label: 'Type de moto',
    car_brand_label: 'Marque de voiture',
    car_model_label: 'Modèle de voiture',
    year_label: 'Année',
    show_all_brands: 'Afficher toutes les marques',
    search_brands: 'Rechercher des marques...',
    select_brand_first: 'Sélectionner d\'abord la marque',
    select_year: 'Sélectionner l\'année',
    vehicle_information_title: 'Informations sur le véhicule',
    accurate_details_better_service: 'Des détails précis du véhicule nous aident à fournir un meilleur service',
    pricing_may_vary_by_size: 'Les prix peuvent varier selon la taille et le type de véhicule',
    all_vehicle_types_welcome: 'Tous les types de véhicules sont les bienvenus',
    please_select_vehicle_type: 'Veuillez sélectionner le type de véhicule',
    loading: 'Chargement',
    loading_models: 'Chargement des modèles',
    loading_brands: 'Chargement des marques',
    popular_brands: 'Marques populaires',
    no_brands_found: 'Aucune marque trouvée correspondant à',
    selected_vehicle: 'Véhicule sélectionné :',
    // Vehicle Information
    vehicle_info_card_title: 'Informations sur le véhicule',
    accurate_vehicle_details: 'Des détails précis du véhicule nous aident à fournir un meilleur service',
    pricing_varies_by_vehicle: 'Les prix peuvent varier selon la taille et le type de véhicule',
    all_vehicles_welcome: 'Tous les types de véhicules sont les bienvenus',
    // Service Workers Screen
    providers: 'Prestataires',
    loading_workers: 'Chargement des prestataires...',
    error_loading_workers: 'Erreur de chargement des prestataires',
    failed_to_load_workers: 'Échec du chargement des prestataires. Veuillez réessayer.',
    no_providers_found: 'Aucun prestataire trouvé pour ce service',
    try_checking_back_later: 'Essayez de revenir plus tard ou sélectionnez un autre service',
    refresh: 'Actualiser',
    reviews: 'avis',
    years_exp: 'ans d\'exp',
    available: 'Disponible',
    busy: 'Occupé',
    services_label: 'Services :',
    service_not_loaded_properly: 'Service non chargé correctement. Veuillez réessayer.',
    // Worker Dashboard Screen
    welcome_back_worker: 'Bon retour',
    dashboard_overview: 'Voici un aperçu de votre tableau de bord',
    todays_earnings: 'Gains d\'aujourd\'hui',
    this_week: 'Cette semaine',
    rating: 'Note',
    loading_bookings: 'Chargement des réservations...',
    manage_bookings: 'Gérer les réservations',
    view_manage_all_bookings: 'Voir et gérer toutes vos réservations',
    recent_activity: 'Activité récente',
    view_all: 'Voir tout',
    accept_booking: 'Accepter la réservation',
    accept_booking_confirm: 'Êtes-vous sûr de vouloir accepter cette réservation ?',
    accept: 'Accepter',
    success: 'Succès',
    booking_accepted: 'Réservation acceptée !',
    failed_accept_booking: 'Échec de l\'acceptation de la réservation',
    reject_booking: 'Rejeter la réservation',
    reject_booking_confirm: 'Êtes-vous sûr de vouloir rejeter cette réservation ?',
    reject: 'Rejeter',
    rejected: 'Rejetée',
    booking_rejected: 'Réservation rejetée.',
    failed_reject_booking: 'Échec du rejet de la réservation',
    complete_booking: 'Terminer la réservation',
    complete_booking_confirm: 'Marquer cette réservation comme terminée ?',
    complete: 'Terminer',
    booking_completed: 'Réservation terminée !',
    failed_complete_booking: 'Échec de la finalisation de la réservation',
    start_booking: 'Commencer ',
    start_booking_confirm: 'Marquer cette réservation comme en cours ?',
    start: 'Commencer',
    booking_started: 'Réservation commencée !',
    failed_start_booking: 'Échec du démarrage de la réservation',
    completed: 'Terminée',
    customer_contact_info: 'Informations de contact du client',
    rating_stars: 'étoiles',
    mark_complete: 'Marquer comme terminé',
    user_not_authenticated: 'Utilisateur non authentifié',
    failed_load_worker_data: 'Échec du chargement des données du prestataire',
    // Worker Bookings Screen
    failed_load_bookings: 'Échec du chargement des réservations',
    unavailable: 'Indisponible',
    customer_phone_not_available: 'Numéro de téléphone du client non disponible.',
    unable_to_open_phone_app: 'Impossible d\'ouvrir l\'application téléphone.',
    booking_accepted_successfully: 'Réservation acceptée avec succès !',
    failed_accept_booking_short: 'Échec de l\'acceptation de la réservation',
    notice: 'Avis',
    booking_marked_completed: 'Réservation marquée comme terminée !',
    failed_complete_booking_short: 'Échec de la finalisation de la réservation',
    pending: 'En attente',
    active: 'Active',
    in_progress: 'En cours',
    contact_customer: 'Contacter le client',
    customer_rating: 'Note du client',
    no_bookings: 'Aucune réservation {status}',
    new_booking_requests_appear: 'Les nouvelles demandes de réservation apparaîtront ici',
    accepted_bookings_show: 'Les réservations acceptées s\'afficheront ici',
    completed_jobs_listed: 'Vos travaux terminés seront listés ici',
    // Vehicle Types
    vehicle_type_sedan: 'Berline',
    vehicle_type_compact: 'Citadine',
    vehicle_type_medium_suv: 'SUV Moyen',
    vehicle_type_large_suv: 'Grand SUV',
    vehicle_type_motorcycle: 'Moto',
    // Services Screen
    please_select_vehicle_type_to_see_services: 'Veuillez sélectionner un type de véhicule pour voir les services disponibles',
    no_services_available_for_vehicle_type: 'Aucun service disponible pour ce type de véhicule',
    price: 'Prix',
    duration: 'Durée',
    no_inclusions_available: 'Aucune information d\'inclusions disponible',
    book_this_service: 'Réserver ce service',
    // Entry Screen Bubbles
    map: 'Carte',
    entry_basic_title: 'Lavage Basique',
    entry_deluxe_title: 'Lavage Deluxe',
    entry_deep_title: 'Nettoyage Profond',
    entry_pro_title: 'Pack Pro',
    entry_express_title: 'Service Express',
    entry_protection_title: 'Protection Peinture',
    // Change Information
    customer_change: 'Le client a',
    change: 'de monnaie',
    // Phone Number Required Modal
    phone_number_required: 'Numéro de téléphone requis',
    phone_number_required_message: 'Un numéro de téléphone est requis pour finaliser votre réservation. Veuillez entrer votre numéro ci-dessous.',
    enter_phone_number_placeholder: '+212 6XX XXX XXX',
    save_phone_number: 'Enregistrer et continuer',
    invalid_phone_number: 'Numéro de téléphone invalide',
    invalid_phone_number_message: 'Veuillez entrer un numéro de téléphone valide.',
    phone_save_failed: 'Échec de l\'enregistrement du numéro. Veuillez réessayer.',
    // Previously missing FR translations (existed in EN only)
    edit_profile: 'Modifier le profil',
    validation_error: 'Erreur de validation',
    address_label_required: 'Le libellé de l\'adresse est requis',
    address_required: 'L\'adresse est requise',
    address_saved: 'Adresse enregistrée',
    address_saved_message: 'Votre adresse a été enregistrée avec succès',
    failed_to_save_address: 'Échec de l\'enregistrement de l\'adresse. Veuillez réessayer.',
    getting_started: 'Premiers pas',
    how_to_book_service: 'Comment réserver un service de lavage auto',
    finding_right_washer: 'Trouver le bon laveur auto',
    understanding_pricing: 'Comprendre les tarifs',
    payment_methods_help: 'Méthodes de paiement',
    managing_bookings: 'Gestion des réservations',
    canceling_rescheduling: 'Annulation ou reprogrammation',
    tracking_booking: 'Suivi de votre réservation',
    rating_reviews: 'Notes et avis',
    booking_history: 'Historique des réservations',
    account_settings: 'Compte & Paramètres',
    help_creating_account: 'Créer un compte',
    managing_profile: 'Gérer votre profil',
    notification_settings: 'Paramètres de notification',
    privacy_security: 'Confidentialité et sécurité',
    troubleshooting: 'Dépannage',
    app_not_working: 'L\'application ne fonctionne pas correctement',
    payment_issues: 'Problèmes de paiement',
    worker_no_show: 'Le prestataire ne s\'est pas présenté',
    quality_concerns: 'Problèmes de qualité',
    live_chat: 'Chat en direct',
    chat_with_support: 'Discuter avec notre équipe support',
    call_us: 'Appelez-nous',
    email_support: 'Support par email',
    emergency_contact: 'Contact d\'urgence',
    call_emergency_hotline: 'Appeler la ligne d\'urgence ?',
    urgent_safety_concern: 'Si vous avez une préoccupation urgente de sécurité ou une urgence, veuillez nous contacter immédiatement.',
    emergency_hotline: 'Ligne d\'urgence',
    help_topic: 'Sujet d\'aide',
    information_about: 'Informations sur : {item}',
    feature_available_soon: 'Cette fonctionnalité sera bientôt disponible avec un contenu d\'aide détaillé.',
    chat_feature_soon: 'La fonctionnalité de chat sera bientôt disponible',
    en: 'Anglais',
    // Keys used in screens but previously undefined in both EN and FR
    address: 'Adresse',
    and: 'et',
    arrival_confirmed: 'Arrivée confirmée',
    arrived_at_location: 'Arrivé sur place',
    at_point: 'à',
    available_services: 'Services disponibles',
    booking_rescheduled_and_accepted: 'Réservation reprogrammée et acceptée',
    call_failed: 'Appel échoué',
    confirm: 'Confirmer',
    confirm_arrival: 'Confirmer l\'arrivée',
    continue_with_google: 'Continuer avec Google',
    copy_number: 'Copier le numéro',
    create_new_password: 'Créer un nouveau mot de passe',
    enter_new_password: 'Entrez le nouveau mot de passe',
    enter_valid_phone_number: 'Veuillez entrer un numéro de téléphone valide',
    error_loading_worker: 'Erreur lors du chargement des détails du prestataire',
    loading_reviews: 'Chargement des avis...',
    location_required: 'La localisation est requise',
    new_password: 'Nouveau mot de passe',
    new_password_instructions: 'Entrez votre nouveau mot de passe ci-dessous',
    no_phone: 'Aucun numéro de téléphone disponible',
    no_results_found: 'Aucun résultat trouvé',
    no_reviews_yet: 'Aucun avis pour le moment',
    no_services_available: 'Aucun service disponible',
    ok: 'OK',
    open_from_email_link: 'Veuillez ouvrir cette page depuis le lien dans votre email',
    or: 'ou',
    overall_rating: 'Note globale',
    password_too_short: 'Le mot de passe doit contenir au moins 6 caractères',
    password_update_failed: 'Échec de la mise à jour du mot de passe',
    password_update_success: 'Mot de passe mis à jour',
    password_updated: 'Votre mot de passe a été mis à jour avec succès',
    passwords_dnot_match: 'Les mots de passe ne correspondent pas',
    phone_not_available: 'Numéro de téléphone non disponible',
    phone_number_required_for_booking: 'Requis pour vous contacter concernant votre réservation',
    please_select_address_or_use_map: 'Veuillez sélectionner une adresse ou utiliser la carte',
    please_select_vehicle_type_first: 'Veuillez d\'abord sélectionner un type de véhicule',
    popular_services: 'Services populaires',
    reenter_new_password: 'Ressaisissez le nouveau mot de passe',
    reset_failed: 'Échec de la réinitialisation',
    reset_instructions_sent: 'Les instructions de réinitialisation ont été envoyées à votre email',
    reset_sent: 'Réinitialisation envoyée',
    reviewed: 'Évalué',
    saving: 'Enregistrement...',
    select_model: 'Sélectionner le modèle',
    selected_service_not_found: 'Service sélectionné introuvable',
    sending: 'Envoi...',
    service_details: 'Détails du service',
    session_not_ready: 'Session non prête. Veuillez réessayer.',
    set_new_password: 'Définir un nouveau mot de passe',
    specialties: 'Spécialités',
    step_3_of_5_select_services: 'Étape 3 sur 5 : Sélection des services',
    tap_to_select: 'Appuyez pour sélectionner',
    type_message: 'Écrire un message...',
    update_password: 'Mettre à jour le mot de passe',
    failed_mark_arrival: 'Échec de la confirmation d\'arrivée',
    failed_reschedule_accept: 'Échec de la reprogrammation et acceptation',
    // ChangePasswordScreen
    update_your_password: 'Mettre à jour votre mot de passe',
    enter_current_and_new: 'Entrez votre mot de passe actuel et votre nouveau mot de passe.',
    current_password: 'Mot de passe actuel',
    enter_current_password: 'Entrez le mot de passe actuel',
    confirm_new_password: 'Confirmer le nouveau mot de passe',
    confirm_new_password_placeholder: 'Confirmez le nouveau mot de passe',
    updating: 'Mise à jour...',
    password_changed: 'Mot de passe modifié',
    password_changed_message: 'Votre mot de passe a été mis à jour avec succès. Vous serez redirigé vers l\'écran de connexion pour vous connecter avec votre nouveau mot de passe.',
    go_to_login: 'Aller à la connexion',
    // ForgotPasswordScreen
    please_wait: 'Veuillez patienter',
    too_many_requests: 'Trop de demandes',
    // ManageBookingScreen
    manage_booking: 'Gérer la réservation',
    // AddressScreens
    // BookingReviewScreen
    review_booking: 'Vérifier la réservation',
    // NotificationsScreen
    booking_confirmed_notif: 'Réservation confirmée',
    booking_completed_notif: 'Réservation terminée',
    promo: 'Promo',
    support_notif: 'Support',
    // ProfileScreen
    copy_token: 'Copier le jeton',
    // ResetPasswordScreen
    session_expired: 'Session expirée',
    // ForgotPasswordScreen
    reset_password: 'Réinitialiser le mot de passe',
    reset_instructions: 'Entrez votre email et nous vous enverrons les instructions pour réinitialiser votre mot de passe',
    reset_method: 'Méthode de réinitialisation',
    email_address: 'Adresse email',
    send_reset_instructions: 'Envoyer les instructions',
    back_to_sign_in: 'Retour à la connexion',
    rate_limit_message: 'Limite de demandes atteinte. Veuillez patienter quelques minutes avant de réessayer.',
  },
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage, persist?: boolean) => Promise<void>;
  t: (key: string) => string;
  languageLabel: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const initial = (user?.profile?.language_preference as AppLanguage) || 'fr';
  const [language, setLangState] = useState<AppLanguage>(initial);

  useEffect(() => {
    if (user?.profile?.preferred_language && user.profile.preferred_language !== language) {
      setLangState(user.profile.preferred_language as AppLanguage);
    }
  }, [user?.profile?.preferred_language]);

  const setLanguage = async (lang: AppLanguage, persist: boolean = true) => {
    setLangState(lang);
    if (persist && user?.id) {
      try {
        await authService.updateProfile(user.id, { preferred_language: lang } as any);
      } catch (e) {
        // noop
      }
    }
  };

  const t = (key: string) => {
    const dict = dictionaries[language] || dictionaries.en;
    return dict[key] ?? key;
  };

  const languageLabel = useMemo(() => {
    const labelsInUILang: Record<AppLanguage, Record<AppLanguage, string>> = {
      en: { en: 'English', fr: 'Français' },
      fr: { en: 'Anglais', fr: 'Français' },
    };
    return labelsInUILang[language]?.[language] || 'English';
  }, [language]);

  const value: LanguageContextType = { language, setLanguage, t, languageLabel };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
